### ISSUE TITLE
Training the model

### ISSUE THREAD

**Issue by vedasreeb29** [akshatchhabra/TransLRPL#10]

**Comment by vedasreeb29** [comment]
When trying to run the command for training, the code wasn't able to find the files train.csharp_monolingual.pth in the given data path.

**Comment by vedasreeb29** [comment]
> When trying to run the command for training, the code wasn't able to find the files train.csharp_monolingual.pth in the given data path.

Had renamed the files generated from preprocessing(as train.csharp_monolingual.0.pth) to required name and that error was resolved.

**Comment by vedasreeb29** [comment]
Getting this error now
Loading miniconda version 22.11.1-1
Traceback (most recent call last):
  File "codegen_sources/model/train.py", line 854, in <module>
    main(params)
  File "codegen_sources/model/train.py", line 688, in main
    init_distributed_mode(params)
  File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransLRPL/CodeGen/codegen_sources/model/src/slurm.py", line 95, in init_distributed_mode
    params.world_size = int(os.environ["SLURM_NTASKS"])
  File "/home/vbojanapally_umass_edu/.conda/envs/transCoder_env/lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLURM_NTASKS'

**Comment by vedasreeb29** [comment]
> Getting this error now Loading miniconda version 22.11.1-1 Traceback (most recent call last): File "codegen_sources/model/train.py", line 854, in main(params) File "codegen_sources/model/train.py", line 688, in main init_distributed_mode(params) File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransLRPL/CodeGen/codegen_sources/model/src/slurm.py", line 95, in init_distributed_mode params.world_size = int(os.environ["SLURM_NTASKS"]) File "/home/vbojanapally_umass_edu/.conda/envs/transCoder_env/lib/python3.7/os.py", line 679, in **getitem** raise KeyError(key) from None KeyError: 'SLURM_NTASKS'

Following this(https://stackoverflow.com/questions/66879939/i-got-no-output-using-echo-slurm-ntasks), configured the no.of tasks while launching the batch job and this resolved the error
