### ISSUE TITLE
TransCoder hello world

### ISSUE THREAD

**Issue by akshatchhabra** [akshatchhabra/TransLRPL#3]
Run TransCoder on test dataset (https://github.com/facebookresearch/CodeGen/tree/main/data/test_dataset)

1. install dependencies: https://github.com/facebookresearch/CodeGen#dependencies
2. preprocess data: https://github.com/facebookresearch/CodeGen#dataset-preprocessing
3. train the model: https://github.com/facebookresearch/CodeGen#model

**Comment by akshatchhabra** [comment]
error installing NVIDIA apex

```
Processing /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/apex
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/apex/setup.py", line 130, in <module>
      _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
    File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/apex/setup.py", line 17, in get_cuda_bare_metal_version
      raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
  TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'


  torch.__version__  = 1.9.0+cu102


  Preparing metadata (setup.py) ... error
WARNING: Discarding file:///work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/apex. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by akshatchhabra** [comment]
Had to use pip to install libraries instead of conda
Rest of install_env.sh ran without any issues

Tried running pipeline.py on the test datasets available in the CodeGen repo but got the following error:
```Traceback (most recent call last):
  File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/codegen_sources/preprocessing/preprocess.py", line 214, in <module>
    preprocess(args)
  File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/codegen_sources/preprocessing/preprocess.py", line 105, in preprocess
    executor=cluster_apply_bpe, local_parallelism=args.local_parallelism
  File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/codegen_sources/preprocessing/dataset_modes/dataset_mode.py", line 617, in apply_bpe
    job.result()
  File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/core.py", line 266, in result
    r = self.results()
  File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/core.py", line 294, in results
    raise job_exception  # pylint: disable=raising-bad-type
submitit.core.utils.FailedJobError: Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/codegen_sources/preprocessing/bpe_modes/fast_bpe_mode.py", line 93, in apply_bpe_file
    ), f"failed to apply bpe on {file}, command: \n {FAST} applybpe {output} {file} {self.codes} {vocab if self.use_vocab else ''}"
AssertionError: failed to apply bpe on /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/data/test_dataset/cpp.train.cl.0.tok, command:
 /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/fastBPE/fast applybpe /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/data/test_dataset/cpp.train.cl.0.bpe /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/data/test_dataset/cpp.train.cl.0.tok /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/data/test_dataset/cpp-java.sa-cl.codes```

**Comment by akshatchhabra** [comment]
> Had to use pip to install libraries instead of conda Rest of install_env.sh ran without any issues
> 
> Tried running pipeline.py on the test datasets available in the CodeGen repo but got the following error:
> 
> ```
>   File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/codegen_sources/preprocessing/preprocess.py", line 214, in <module>
>     preprocess(args)
>   File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/codegen_sources/preprocessing/preprocess.py", line 105, in preprocess
>     executor=cluster_apply_bpe, local_parallelism=args.local_parallelism
>   File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/codegen_sources/preprocessing/dataset_modes/dataset_mode.py", line 617, in apply_bpe
>     job.result()
>   File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/core.py", line 266, in result
>     r = self.results()
>   File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/core.py", line 294, in results
>     raise job_exception  # pylint: disable=raising-bad-type
> submitit.core.utils.FailedJobError: Job (task=0) failed during processing with trace:
> ----------------------
> Traceback (most recent call last):
>   File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/submission.py", line 54, in process_job
>     result = delayed.result()
>   File "/home/akshatchhabr_umass_edu/.conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/utils.py", line 133, in result
>     self._result = self.function(*self.args, **self.kwargs)
>   File "/work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/codegen_sources/preprocessing/bpe_modes/fast_bpe_mode.py", line 93, in apply_bpe_file
>     ), f"failed to apply bpe on {file}, command: \n {FAST} applybpe {output} {file} {self.codes} {vocab if self.use_vocab else ''}"
> AssertionError: failed to apply bpe on /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/data/test_dataset/cpp.train.cl.0.tok, command:
>  /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/fastBPE/fast applybpe /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/data/test_dataset/cpp.train.cl.0.bpe /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/data/test_dataset/cpp.train.cl.0.tok /work/pi_adrozdov_umass_edu/akshatchhabr_umass_edu/TransCoder_Test/CodeGen/data/test_dataset/cpp-java.sa-cl.codes```
> ```

issue can be resolved by using a larger dataset/reducing the BPE codes that need to be learnt. (https://github.com/facebookresearch/CodeGen/issues/6#issuecomment-895174678)
