### ISSUE TITLE
Running the pre_procesing pipeline

### ISSUE THREAD

**Issue by vedasreeb29** [akshatchhabra/TransLRPL#9]

**Comment by vedasreeb29** [comment]
While trying to run the pipeline, it was returning the following error
INFO - 04/02/23 16:53:31 - 0:00:00 - Dataset pipeline for /work/pi_adrozdov_umass_edu/transLRPL/train_dataset_json
Traceback (most recent call last):
  File "/home/vbojanapally_umass_edu/.conda/envs/transCoder_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vbojanapally_umass_edu/.conda/envs/transCoder_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/work/pi_adrozdov_umass_edu/transLRPL/TransLRPL/CodeGen/codegen_sources/preprocessing/preprocess.py", line 214, in <module>
    preprocess(args)
  File "/work/pi_adrozdov_umass_edu/transLRPL/TransLRPL/CodeGen/codegen_sources/preprocessing/preprocess.py", line 91, in preprocess
    keep_comments=args.keep_comments,
  File "/work/pi_adrozdov_umass_edu/transLRPL/TransLRPL/CodeGen/codegen_sources/preprocessing/dataset_modes/monolingual_mode.py", line 46, in __init__
    keep_comments=keep_comments,
  File "/work/pi_adrozdov_umass_edu/transLRPL/TransLRPL/CodeGen/codegen_sources/preprocessing/dataset_modes/dataset_mode.py", line 89, in __init__
    self.initialize_processor()
  File "/work/pi_adrozdov_umass_edu/transLRPL/TransLRPL/CodeGen/codegen_sources/preprocessing/dataset_modes/dataset_mode.py", line 102, in initialize_processor
    for lang in self.languages
  File "/work/pi_adrozdov_umass_edu/transLRPL/TransLRPL/CodeGen/codegen_sources/preprocessing/dataset_modes/dataset_mode.py", line 102, in <dictcomp>
    for lang in self.languages
KeyError: 'csharp'

**Comment by vedasreeb29** [comment]
> 

This got resolved by importing the newly added language processors in the dataset_mode.py file

**Comment by vedasreeb29** [comment]
Also, the dataset file names had to be in a specific format as to <language_name>.<number>.json.gz. Hence, had to update the pre processing scripts to be able to run the pipeline.
